name: flutter_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  timer_count_down: ^2.2.0
  timer_builder: ^2.0.0
  intl: ^0.17.0
  flutter_circular_slider: ^2.5.0
  animated_button: ^0.2.0
  argon_buttons_flutter: ^1.0.6
  flutter_spinkit: ^5.0.0
  rxdart: ^0.27.1
  url_launcher: ^6.0.9
  shared_preferences: ^2.0.6
  connectivity: ^3.0.6
  sleek_circular_slider: ^2.0.1
  web_socket_channel: ^2.1.0
  socket_io_client: ^1.0.1
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  scroll_snap_list: ^0.8.2
  wave: ^0.2.0
  flutter_xlider: ^3.4.0
  hive_generator: ^1.1.0
  build_runner: ^2.0.6
  wifi_iot: ^0.3.4
  f_logs: ^2.0.0
  path_provider: ^2.0.2
  permission_handler: ^8.1.4+1
  #ext_storage: ^1.0.3
  lamp_bottom_navigation: ^0.1.1
  carousel_slider: ^4.0.0
  dio: ^4.0.4
  pausable_timer: ^1.0.0+3




  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets\Screenshot (27).png
    - assets\scene1.png
    - assets\scene2.png
    - assets\scene3.png
    - assets\scene4.png
    - assets\scene5.png
    - assets\scene6.png
    - assets\scene7.png
    - assets\scene8.png
    - assets\scene9.png
    - assets\scene10.png
    - assets\fan.png
    - assets\fan1.png
    - assets\back.jpeg
    - assets\tech.png
    - assets\tech1.png
    - assets\tech2.png
    - assets\rightarrow.png
    - assets\leftarrow.png
    - assets\emergency.png
    - assets\power.png
    - assets\curtain_close2.png
    - assets\curtain_open2.png
    - assets\sensor.png
    - assets\lamp1.png
    - assets\bgim.png
    - assets\bgim2.png
    - assets\bgim3.png
    - assets\buddha.png
    - assets\bgbuddha.jpg
    - assets\scrnsvr_buddha.png
    - assets\restrnt_bg.png
    - assets\bgim4.png



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
   - family: IndieFlower
     fonts:
       - asset: fonts/IndieFlower-Regular.ttf
   - family: Astrolab
     fonts:
       - asset: fonts/Astrolab.ttf
   - family: FredokaOne
     fonts:
       - asset: fonts/FredokaOne-Regular.ttf
       - weight: 700

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
